In [1]:
import sklearn

**sklearn 기능 종합**

|분류|모듈|설명|
|:--:|:--:|:--|
|예제 데이터|sklearn.datasets|scikit-learn에 내장되어 예제 데이터 세트를 제공함|
|변수 처리|sklearn.preprocessing|데이터 전처리에 필요한 다양한 기능을 제공함(인코딩, 정규화, 스케일링 등)|
||sklearn.fature_selection|알고리즘에 큰 영향을 미치는 변수들을 선택하는 작업을 수행하는 다양한 기능 제공|
||sklearn.feature_extraction|- 텍스트 데이터나 이미지 데이터와 같이 벡터화된 변수를 추출하는 데 사용 <br>- 예를 들어 텍스트 데이터에서 Count Vectorizer 등을 생성하는 기능 제공 <br>- 텍스트 데이터의 변수 추출은 sklearn.feature_extraction.text 모듈에, 이미지 데이터의 변수 추출은 sklearn.feature_extraction.image 모듈에 함수가 내장되어 있음|
|변수 처리 & 차원 축소|sklearn.decomposition|- 차원 축소와 관련한 알고리즘 지원 <br>-PCA, NMF, Truncated SVD 등을 통해 차원 축소 기능을 수행할 수 있음|
|데이터 분리, 검증 & 매개변수 튜닝|sklearn.model_selection|-학습데이터와 검증 데이터, 예측 데이터로 데이터를 분리하기 위해 활용하는 train_test_split 함수가 내장 <br>-최적의 하이퍼 매개변수로 모델을 평가하기 위한 다양한 함수와 기능 제공|
|평가|sklearn.metrics|-분류, 회귀, 클러스터링 등에 대한 다양한 성능 측정 방법 제공 <br>- 모델 평가를 위한 Accuracy, Precision, Recall, ROC-AUC, RMSE 등을 제공|
|머신러닝 알고리즘|sklearn.ensemble|-앙상블 알고리즘 <br>- RandomForest, AdaBoost, Gradient Boosting|
||sklearn.linear_model|- 선형회귀, 릿지, 라쏘 및 로지스틱 회귀 등 회귀 관련 알고리즘 지원 <br>- SGD 관련 알고리즘 제공|
||sklearn.naive_bayes|나이브 베이즈 알고리즘 제공, 가우시안 NB, 다항 분포 NB|
||sklearn.neighbors|- 최근접 이웃 알고리즘 제공 <br>- K-NN 등|
||sklearn.svm|서포트 벡터 머신 알고리즘|
||sklearn.tree|- 트리 기반 머신러닝 알고리즘 제공 <br>- 의사결정 트리 알고리즘|
||sklearn.cluster|- 비지도 클러스터링 알고리즘 제공 <br>- K-means, 계층형, DBSCAN 등|
|유틸리티|sklearn.pipeline|변수 처리와 같은 변환 작업과 머신러닝 알고리즘 학습, 예측 등 머신러닝 프로세스를 함께 묶어서 실행할 수 있는 유틸리티 제공|


### iris dataset

In [2]:
# 붓꽃 데이터셋 불러오기
from sklearn.datasets import load_iris

iris = load_iris()
print('붓꽃 데이터세트 타입 : ', type(iris))

keys = iris.keys()
print('붓꽃 데이터세트 키 : ', keys)

붓꽃 데이터세트 타입 :  <class 'sklearn.utils.Bunch'>
붓꽃 데이터세트 키 :  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
# 붓꽃 데이터세트 키 출력
print('feature_names : ')
print(iris.feature_names)

print('\ntarget_names : ')
print(iris.target_names)

print('\ndata : ')
print(iris.data)

print('\ntarget : ')
print(iris.target)

feature_names : 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

target_names : 
['setosa' 'versicolor' 'virginica']

data : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [

### scikit - learn 머신러닝 만들어보기

In [4]:
# 붓꽃 데이터셋 훑어보기
import pandas as pd

iris_df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0

[3 rows x 5 columns]

In [5]:
# 학습/테스트 데이터셋 분할
from sklearn.model_selection import train_test_split

iris_data = iris.data
iris_label = iris.target

x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=1)

print('train dataset')
print('x_train dataset : ', len(x_train))
print('y_train dataset : ', len(y_train))

print('\ntest datset')
print('x_test dataset : ', len(x_test))
print('y_test dataset : ', len(y_test))

train dataset
x_train dataset :  120
y_train dataset :  120

test datset
x_test dataset :  30
y_test dataset :  30


In [6]:
# 의사결정 트리 머신러닝 학습
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=11)

In [7]:
# 의사결정 트리 머신러닝 테스트/평가
from sklearn.metrics import accuracy_score

pred = dt_clf.predict(x_test)
ac_score = accuracy_score(y_test, pred)

print('예측 정확도 : ', ac_score)

예측 정확도 :  0.9666666666666667


---
### scikit-learn 데이터 전처리 
### 1. 레이블 인코딩

In [8]:
# label encoding
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', 'TV', '냉장고', '컴퓨터', '컴퓨터']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값 : ', labels)
print('인코딩 클래스 : ', encoder.classes_)

인코딩 변환값 :  [0 1 2 3 0 1 3 3]
인코딩 클래스 :  ['TV' '냉장고' '전자레인지' '컴퓨터']


In [9]:
# label decoding
origins = encoder.inverse_transform([0, 1, 2, 3, 0, 1, 3, 3])

print('디코딩 원본값 : ', origins)

디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' 'TV' '냉장고' '컴퓨터' '컴퓨터']


### 2. 원-핫 인코딩

In [11]:
# One-Hot encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(8, 4)


In [12]:
# 판다스의 원-핫 인코딩
import pandas as pd

item_df = pd.DataFrame({'item': items})
pd.get_dummies(item_df)

item_TV  item_냉장고  item_전자레인지  item_컴퓨터
0        1         0           0         0
1        0         1           0         0
2        0         0           1         0
3        0         0           0         1
4        1         0           0         0
5        0         1           0         0
6        0         0           0         1
7        0         0           0         1

### 3. 스케일링

In [13]:
# 스케일링 데이터 세트 훑어보기
from sklearn.datasets import load_iris
import pandas as pd
 
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns=iris.feature_names)

print('feature 들의 평균 값 :\n', iris_df.mean())
print('feature 들의 분산 값 :\n', iris_df.var())

feature 들의 평균 값 :
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
feature 들의 분산 값 :
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [15]:
# 표준화
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 평균 값 : \n', iris_df_scaled.mean())
print('feature 들의 분산 값 : \n', iris_df_scaled.var())

feature 들의 평균 값 : 
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature 들의 분산 값 : 
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [16]:
# 최대-최소 정규화
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns=iris.feature_names)

print('feature 들의 최소 값 : \n', iris_df_scaled.min())
print('feature 들의 최대 값 : \n', iris_df_scaled.max())

feature 들의 최소 값 : 
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature 들의 최대 값 : 
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


### 스케일링 주의사항 
- train dataset에 fit 한 스케일러를 그대로 test dataset에 적용해야 한다. 
- or Not? 
    - train과 test 데이터셋의 스케일링 기준 정보가 달라져서 예측이 정상적으로 이루어지지 않을 수 있다. 

In [17]:
# 스케일링 주의사항
from sklearn.preprocessing import MinMaxScaler
import numpy as np

train_array = np.arange(0,11).reshape(-1, 1)
test_array = np.arange(0, 6).reshape(-1, 1)

scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('Scaled train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))

#scaler.fit(test_array)
test_scaled = scaler.transform(test_array)

print('\n원본 test_array 데이터 : ', np.round(test_array.reshape(-1), 2))
print('Scaled test_array 데이터 : ', np.round(test_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
Scaled train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터 :  [0 1 2 3 4 5]
Scaled test_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5]
