## 빅데이터 분석기사 실기 
- Penguins : 남극 펭귄 신체 크기와 무게에 대한 7가지 정도의 데이터

In [57]:
import pandas as pd
import numpy as np

In [58]:
import warnings
warnings.filterwarnings('ignore')

## 1. 데이터 불러오기

In [59]:
X_test = pd.read_csv('/Users/hayeon/Downloads/penguin_X_test.csv')
X_train = pd.read_csv('/Users/hayeon/Downloads/penguin_X_train.csv')
y_train = pd.read_csv('/Users/hayeon/Downloads/penguin_y_train.csv')

## 2. 데이터 전처리

In [60]:
print(X_train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            240 non-null    object 
 1   island             240 non-null    object 
 2   sex                232 non-null    object 
 3   bill_length_mm     238 non-null    float64
 4   bill_depth_mm      238 non-null    float64
 5   flipper_length_mm  238 non-null    float64
dtypes: float64(3), object(3)
memory usage: 11.4+ KB
None


### 결측치 확인할 때 y_train 붙여서 확인해야 한다고 함
- why???

In [61]:
train = pd.concat([X_train, y_train], axis=1)

In [62]:
print(train.loc[(train.sex.isna()) | (train.bill_length_mm.isna()) | (train.bill_depth_mm.isna())|
               (train.flipper_length_mm.isna()) | (train.body_mass_g.isna())])

    species     island  sex  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen  NaN            42.0           20.2              190.0   
6    Gentoo     Biscoe  NaN            44.5           14.3              216.0   
43   Gentoo     Biscoe  NaN             NaN            NaN                NaN   
66   Adelie  Torgersen  NaN            37.8           17.3              180.0   
88   Gentoo     Biscoe  NaN            47.3           13.8              216.0   
89   Adelie  Torgersen  NaN            37.8           17.1              186.0   
110  Gentoo     Biscoe  NaN            44.5           15.7              217.0   
229  Adelie  Torgersen  NaN             NaN            NaN                NaN   

     body_mass_g  
0         4250.0  
6         4100.0  
43           NaN  
66        3700.0  
88        4725.0  
89        3300.0  
110       4875.0  
229          NaN  


In [63]:
# 결측치가 다 같은 행에서들 발견되었기 때문에 drop
train = train.dropna()
train.reset_index(drop=True, inplace=True)

In [64]:
X_train = train[['species', 'island', 'sex', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']]
y_train = train[['body_mass_g']]

In [65]:
# 수치형 범위가 다르니 스케일링 해야 함
print(X_train.describe())

       bill_length_mm  bill_depth_mm  flipper_length_mm
count      232.000000     232.000000         232.000000
mean        43.990948      17.226293         200.681034
std          5.509760       1.964677          14.064231
min         32.100000      13.200000         172.000000
25%         39.200000      15.700000         190.000000
50%         44.950000      17.350000         197.000000
75%         48.775000      18.725000         212.250000
max         58.000000      21.500000         231.000000


In [66]:
COL_DEL = []
COL_NUM = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm'] # 수치형 변수
COL_CAT = ['species', 'island', 'sex'] # 범주형 변수
COL_Y = ['body_mass_g']

In [67]:
# label encoding
X = pd.concat([X_train, X_test]) # 모든 범주형을 체크해야 하니까 합쳐서 ohe fit

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore') # 처리 이후에 새로 등장하는 범주가 없을 예정이니 ignore
ohe.fit(X[COL_CAT])

X_train_res = ohe.transform(X_train[COL_CAT])
X_test_res = ohe.transform(X_test[COL_CAT])

In [68]:
print(X_train_res)

  (0, 2)	1.0
  (0, 3)	1.0
  (0, 6)	1.0
  (1, 0)	1.0
  (1, 5)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 4)	1.0
  (2, 7)	1.0
  (3, 2)	1.0
  (3, 3)	1.0
  (3, 7)	1.0
  (4, 0)	1.0
  (4, 4)	1.0
  (4, 6)	1.0
  (5, 2)	1.0
  (5, 3)	1.0
  (5, 7)	1.0
  (6, 2)	1.0
  (6, 3)	1.0
  (6, 6)	1.0
  (7, 0)	1.0
  (7, 5)	1.0
  (7, 6)	1.0
  (8, 2)	1.0
  :	:
  (223, 6)	1.0
  (224, 2)	1.0
  (224, 3)	1.0
  (224, 7)	1.0
  (225, 0)	1.0
  (225, 4)	1.0
  (225, 7)	1.0
  (226, 1)	1.0
  (226, 4)	1.0
  (226, 7)	1.0
  (227, 1)	1.0
  (227, 4)	1.0
  (227, 6)	1.0
  (228, 2)	1.0
  (228, 3)	1.0
  (228, 7)	1.0
  (229, 0)	1.0
  (229, 5)	1.0
  (229, 6)	1.0
  (230, 1)	1.0
  (230, 4)	1.0
  (230, 6)	1.0
  (231, 2)	1.0
  (231, 3)	1.0
  (231, 6)	1.0


In [69]:
# 위 결과는 np.array이기 때문에 데이터프레임으로 변경시켜줘야 함
X_train_ohe = pd.DataFrame(X_train_res.todense(), columns=ohe.get_feature_names())
X_test_ohe = pd.DataFrame(X_test_res.todense(), columns=ohe.get_feature_names())
print(X_train_ohe)

X_train_fin = pd.concat([X_train[COL_NUM], X_train_ohe], axis=1)
X_test_fin = pd.concat([X_test[COL_NUM], X_test_ohe], axis=1)

     x0_Adelie  x0_Chinstrap  x0_Gentoo  x1_Biscoe  x1_Dream  x1_Torgersen  \
0          0.0           0.0        1.0        1.0       0.0           0.0   
1          1.0           0.0        0.0        0.0       0.0           1.0   
2          0.0           1.0        0.0        0.0       1.0           0.0   
3          0.0           0.0        1.0        1.0       0.0           0.0   
4          1.0           0.0        0.0        0.0       1.0           0.0   
..         ...           ...        ...        ...       ...           ...   
227        0.0           1.0        0.0        0.0       1.0           0.0   
228        0.0           0.0        1.0        1.0       0.0           0.0   
229        1.0           0.0        0.0        0.0       0.0           1.0   
230        0.0           1.0        0.0        0.0       1.0           0.0   
231        0.0           0.0        1.0        1.0       0.0           0.0   

     x2_FEMALE  x2_MALE  
0          1.0      0.0  
1          

### cf. todense() 역할?

In [70]:
print(X_train_res[:5]) # 1이 들어있는 위치만 보여줌 

  (0, 2)	1.0
  (0, 3)	1.0
  (0, 6)	1.0
  (1, 0)	1.0
  (1, 5)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 4)	1.0
  (2, 7)	1.0
  (3, 2)	1.0
  (3, 3)	1.0
  (3, 7)	1.0
  (4, 0)	1.0
  (4, 4)	1.0
  (4, 6)	1.0


In [71]:
X_train_res.todense() # 위 X_train_res를 토대로 좌표 있으면 1, 좌표 없으면 0 채워넣어서 매트릭스 만들기 

matrix([[0., 0., 1., ..., 0., 1., 0.],
        [1., 0., 0., ..., 1., 0., 1.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [1., 0., 0., ..., 1., 1., 0.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 0., 1., 0.]])

---
### 4. 데이터 모형 구축

In [72]:
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(X_train_fin, y_train, test_size=0.3)

In [73]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# fit 할 때는 X_tr 데이터셋을 기준으로 함 -> 평균과 분산에 영향을 미치는 데이터 누수가 발생하지 않게
scaler.fit(X_tr[COL_NUM])
X_tr[COL_NUM] = scaler.transform(X_tr[COL_NUM])
X_val[COL_NUM] = scaler.transform(X_val[COL_NUM])
X_test_fin[COL_NUM] = scaler.transform(X_test_fin[COL_NUM])

In [74]:
from sklearn.linear_model import LinearRegression

modelLR = LinearRegression()
modelLR.fit(X_tr, y_tr)

y_val_pred = modelLR.predict(X_val)
print(y_val_pred)

[[4039.80459995]
 [5590.44999251]
 [3524.97255521]
 [3905.48318893]
 [4945.78100872]
 [5335.75287763]
 [3382.30555509]
 [3474.91586052]
 [3328.94745323]
 [5244.95957381]
 [3926.53275988]
 [3884.83256106]
 [4162.44633274]
 [4053.46020969]
 [4122.44505694]
 [3986.65178876]
 [3448.46553991]
 [5295.88200298]
 [4156.39455693]
 [4077.28114515]
 [3494.43251459]
 [3537.62563654]
 [4734.6700009 ]
 [5523.5810384 ]
 [4211.04713446]
 [4214.233899  ]
 [3212.60014272]
 [3849.88389533]
 [3347.01839848]
 [4747.41878369]
 [4784.93382396]
 [5292.48754645]
 [3454.54882463]
 [3395.16553495]
 [3376.0606055 ]
 [3472.5343464 ]
 [3457.77618486]
 [3484.63121255]
 [3540.5598092 ]
 [3806.41166562]
 [4811.76081968]
 [3950.15348628]
 [3421.3168211 ]
 [3317.34420152]
 [3968.41640332]
 [5386.17068097]
 [4708.90725797]
 [3423.87021243]
 [4196.79114831]
 [5646.47268277]
 [3339.39600018]
 [5412.44169136]
 [3611.28271026]
 [4221.52319887]
 [3450.36855161]
 [3586.65412306]
 [5415.45189282]
 [4017.09659651]
 [4012.6490946

In [75]:
# intercept_
print(modelLR.intercept_) # 절편

coef = pd.Series(data=modelLR.coef_[0], index=X_train_fin.columns) # 기울기
print(coef.sort_values())

[3305.39520774]
x0_Chinstrap        -506.573616
x0_Adelie           -247.173010
x2_FEMALE           -192.367390
x1_Torgersen         -43.141690
x1_Dream               5.574104
x1_Biscoe             37.567587
x2_MALE              192.367390
bill_length_mm       415.937827
bill_depth_mm        445.683230
x0_Gentoo            753.746627
flipper_length_mm    854.585862
dtype: float64


## 해석
- Chinstrap, Adelie 종일수록 무게가 덜 나감
- Gentoo 종이면 다른 종에 비해 무게가 많이 나감
- Female 펭귄이 무게가 덜 나감 
---
### 5. 데이터 모형 평가

In [76]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_val, y_val_pred)
rmse = mean_squared_error(y_val, y_val_pred, squared=False)

print('MSE : %.3f, RMSE : %.3F'%(mse, rmse))

MSE : 97896.964, RMSE : 312.885


In [77]:
# 제출물 만들기
y_pred = modelLR.predict(X_test_fin)
print(y_pred)

[[4038.24504197]
 [5323.31629443]
 [4046.74989462]
 [3484.00964739]
 [4716.20084598]
 [4029.49323052]
 [3334.72342389]
 [3716.98572079]
 [3502.61468281]
 [3531.5034131 ]
 [3429.33349074]
 [5478.48589028]
 [3586.67283438]
 [4001.18616531]
 [3759.7304863 ]
 [4028.43655769]
 [4286.71631632]
 [3464.28770266]
 [3628.81192546]
 [3328.9132463 ]
 [5333.46974525]
 [4092.38231675]
 [5830.54287703]
 [4714.93982969]
 [5378.86427764]
 [5491.03367054]
 [5496.60863868]
 [4123.38643662]
 [3392.8439075 ]
 [4036.67562146]
 [4169.83191373]
 [3455.05345045]
 [3507.74486268]
 [4662.46557624]
 [3405.84535301]
 [3432.11750268]
 [3295.92269804]
 [3366.58226685]
 [3860.19745228]
 [4971.38977137]
 [3530.61812472]
 [5577.55580573]
 [4981.8041114 ]
 [4717.11605314]
 [5734.66212744]
 [3864.57587965]
 [4796.22487608]
 [3314.3747495 ]
 [5386.29469335]
 [4171.21046674]
 [4698.68110515]
 [4772.46303383]
 [4101.33195768]
 [3800.63730282]
 [3303.50499341]
 [4232.61468843]
 [4859.45558792]
 [4653.5517501 ]
 [3799.4465872

In [81]:
pd.DataFrame({'body_mass_g' : y_pred[:, 0]}).to_csv('0040000000.csv', index=False)