In [1]:
import numpy as np

### numpy 배열 생성

In [2]:
a1 = np.array([1, 2, 3])
print(a1)
print('array1 type : ', type(a1))
print('array1 shape : ', a1.shape)

[1 2 3]
array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print('array2 type : ', type(a2))
print('array2 shape : ', a2.shape)

[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)


In [4]:
a3 = np.array([[1, 2, 3]])
print(a3)
print('array3 type : ', type(a3))
print('array3 shape : ', a3.shape)

[[1 2 3]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


### numpy 배열 차원

In [5]:
print('array1 dim : ', a1.ndim)
print('array2 dim : ', a2.ndim)
print('array3 dim : ', a3.ndim)

array1 dim :  1
array2 dim :  2
array3 dim :  2


In [6]:
# numpy arange 함수 기본
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
# numpy arange 함수 응용
a = np.arange(1, 20, 3)
print(a)

[ 1  4  7 10 13 16 19]


- cf. Python 기본 내장 함수인 rage 함수와 동일 기능 

### numpy 배열 초기화

In [8]:
zero_a = np.zeros((2, 5)) # 행, 열
one_a = np.ones((3, 4))

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# numpy zeros_like 함수 
zero_b = np.zeros_like(one_a)
print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
# numpy ones_like 함수 
one_b = np.ones_like(zero_a)
print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# numpy full, random 함수 
full_a = np.full((4, 3), 9) # 4행 3열 행렬을 9로 채우기
random_a = np.random.random((3,4)) # 3행 4열 행렬을 랜덤 실수로 채우기

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.19960189 0.26897281 0.76878785 0.79459951]
 [0.07490439 0.05078073 0.77813199 0.91793392]
 [0.10541102 0.71600317 0.15601655 0.52877168]]


In [12]:
# numpy eye 함수 (대각행렬)
eye_a = np.eye(4)
print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### numpy 배열 크기 변형

In [13]:
# numpy reshape 함수 기본
array1 = np.arange(12)
print('array1 : \n', array1)

array2 = array1.reshape(3,4) # default 행 먼저 채워넣기
print('array2 : \n', array2)

array3 = array1.reshape(3,4, order = 'F') # 열 기준 채워넣기
print('array3 : \n', array3)

array1 : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3 : 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [14]:
# numpy reshape 함수 응용
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim :  2
array2 shape :  (2, 5)


In [16]:
# numpy reshape 함수 다차원 변형
array1 = np.arange(12)
array2 = array1.reshape(2,3,2, order = 'F')

print(array2)
print('array2 dim : ', array2.ndim)
print('array2 shape : ', array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim :  3
array2 shape :  (2, 3, 2)


In [25]:
# numpy flatten 함수 1차원 변형
array3 = array2.flatten()
print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


### numpy 배열 데이터 추출하기
### 1. 인덱싱

In [26]:
# numpy 1차원 배열 단일값 추출
array1 = np.arange(1, 10)
print('array1 : ', array1)

value1 = array1[2]
value2 = array1[-2]

print(value1)
print(value2)

array1 :  [1 2 3 4 5 6 7 8 9]
3
8


In [27]:
# numpy 다차원 배열 단일값 추출
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

value1 = array2[0, 0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1)
print(value2)
print(value3)

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


### 2. 슬라이싱

In [28]:
# numpy 1차원 배열 슬라이싱 추출
array1 = np.arange(1, 10)
array2 = array1[0:3]
array3 = array1[:3]
array4 = array1[3:]

print(type(array2))
print(array2)
print(array3)
print(array4)

<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


In [31]:
# numpy 다차원 배열 슬라이싱 추출
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print('array2 : \n', array2)

print('array2[0:2, 0:2]\n', array2[0:2, 0:2])
print('array2[1:3, 0:3]\n', array2[1:3, 0:3])
print('array2[:2, 1:]\n', array2[:2, 1:])
print('array2[:2, 0]\n', array2[:2, 0])

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]]
array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2[:2, 1:]
 [[2 3]
 [5 6]]
array2[:2, 0]
 [1 4]


### numpy 선형대수 기본연산
### 1. 행렬 내적(행렬 곱)

In [32]:
# numpy 행렬 내적 계산
array1 = np.array([[1, 2, 3],
                  [4, 5, 6]])
array2 = np.array([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_array = np.dot(array1, array2)
print(dot_array)

[[ 58  64]
 [139 154]]


### 2. 전치 행렬

In [33]:
# numpy 전치 행렬 계산
array1 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
transpose_array = np.transpose(array1)

print(transpose_array)

[[1 4]
 [2 5]
 [3 6]]


### numpy 기술통계
#### 1. 배열 데이터 개수 계산

In [34]:
x = np.array([18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
             2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13])

len(x)

26

#### 2. 평균, 분산, 표준편차 계산

In [35]:
print(np.mean(x))
print(np.var(x))
print(np.std(x))

4.8076923076923075
115.23224852071006
10.734628476137871


#### 3. 최댓값, 최솟값, 중앙값 계산

In [36]:
print(np.max(x))
print(np.min(x))
print(np.median(x))

23
-24
5.0


#### 4. 사분위수 계산

In [37]:
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))

0.0
5.0
10.0
