# Series (시리즈)의 개념
<img src="img/1강/Series개념.jpg" alt="datetime" style="width: 1200px;"/>

# pandas 라이브러리 import 하기

In [1]:
# Python의 리스트(List) 타입의 데이터 생성하기
data = [3, 5, 1, 2]
data

[3, 5, 1, 2]

In [5]:
import pandas as pd

In [21]:
# Pandas의 Series 타입의 데이터 생성하기
pd.Series([3, 5, 1, 2])

0    3
1    5
2    1
3    2
dtype: int64

In [3]:
# pandas 라이브러리 임포트하기 (1)
import pandas

In [4]:
# pandas 라이브러리 임포트하기 (2)
import pandas as pd

In [6]:
pd.Series([3, 5, 1, 2])

0    3
1    5
2    1
3    2
dtype: int64

In [7]:
# pandas 라이브러리 임포트하기 (3)
from pandas import Series

In [8]:
Series([3, 5, 1, 2])

0    3
1    5
2    1
3    2
dtype: int64

#  Series 생성
 - 1차원 데이터를 저장하는 파이썬의 데이터타입인 리스트, 튜플, 사전 타입 등을 이용해서 Series 객체를 생성해 보고, Series 객체의 특징들을 살펴보도록 하겠습니다. 

### 1) List를 사용하여 Series 생성하기

In [9]:
data

[3, 5, 1, 2]

In [10]:
data1 = Series(data)
data1

0    3
1    5
2    1
3    2
dtype: int64

In [11]:
data1.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
data1.index = ['a','b','c','d']
data1 # 개수에 맞춰서 인덱스 적어야 함. 개수에 맞지 않으면 에러난다.

a    3
b    5
c    1
d    2
dtype: int64

In [13]:
data1 = Series(data, index = ['a','b','c','d'])
data1

a    3
b    5
c    1
d    2
dtype: int64

### 2) Tuple을 사용하여 Series 생성하기

In [14]:
arr2 = (3, 5, 1, 2)

In [15]:
type(arr2)

tuple

In [17]:
data2 = Series(arr2)
data2

0    3
1    5
2    1
3    2
dtype: int64

### 3) Dict 타입의 변수를 사용하여 Series 생성하기

In [34]:
arr3 = {'a':3,'b':5, 'c':1, 'd':2}

In [35]:
arr3

{'a': 3, 'b': 5, 'c': 1, 'd': 2}

In [36]:
type(arr3)

dict

In [37]:
data3 = Series(arr3)
data3

a    3
b    5
c    1
d    2
dtype: int64

In [38]:
data3[3]

2

In [41]:
arr3['a']

3

### ** 몇 가지 Series 특징들 **

- Series.values는 numpy의 ndarray객체입니다. 

In [24]:
data3.values

array([3, 5, 1, 2])

In [26]:
type(data3.values)

numpy.ndarray

- 값에는 모든 데이터 타입 사용이 가능합니다. 

In [27]:
Series([3, 5, 'big','data',[1, 2, 3], (7, 8, 9)])

0            3
1            5
2          big
3         data
4    [1, 2, 3]
5    (7, 8, 9)
dtype: object

# Series의 속성(Attributes)와 함수(Method)들

#### 샘플 데이터 생성
 값과 Index 인자를 사용하여, Series 생성

In [43]:
sample = Series([85, 90, 75, 55, 45, 90, 95, 85, 90, 100], 
               index = ['a','b','c','d','e','f','g','h','i','j'])
sample

a     85
b     90
c     75
d     55
e     45
f     90
g     95
h     85
i     90
j    100
dtype: int64

### 속성(Attribute) = Series가 가지고 있는 객체, 속성(특징) 혹은 간단한 기능을 제공

1) index - Series의 인덱스 (혹은 인덱스 라벨)

In [30]:
sample.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

2) values - Series의 데이터

In [31]:
sample.values

array([ 85,  90,  75,  55,  45,  90,  95,  85,  90, 100])

3) size - Series의 크기 (데이터의 길이)

In [32]:
sample.size

10

4) dtype - Series의 데이터(Series.values)의 데이터 타입
* 정수형 숫자: int64
* 실수형 숫자: float64
* 문자열이거나 2개 이상의 데이터 타입으로 이루어진 경우: 'O' (Object)

In [33]:
sample.dtype

dtype('int64')

In [34]:
type(sample)

pandas.core.series.Series

In [36]:
Series(['a','b','c']).dtype # O = Object라는 의미 

dtype('O')

In [37]:
Series([3, 5.2, 'big','data']).dtype

dtype('O')

In [38]:
Series([5.3, 1]).dtype

dtype('float64')

### 함수(Methods) - Series가 제공하는 다양한 기능 활용
* 함수 호출 시 전달되는 자료들을 인자(argument, parameter)라고 합니다.
* 각 함수들은 정해진 인자들이 있으며, 인자값들을 토대로 함수가 실행됩니다. 
* 동일한 함수라고 하더라도 인자값을 어떻게 설정하느냐에 따라 동작방식은 달라질 수 있습니다. 



1) describe() - 통계 정보를 한 눈에 제공해주는 함수

In [39]:
sample.describe()

count     10.000000
mean      81.000000
std       17.763883
min       45.000000
25%       77.500000
50%       87.500000
75%       90.000000
max      100.000000
dtype: float64

2) 통계함수들 - max(), min(), avg(), ... 

In [40]:
sample.max()

100

In [41]:
sample.min()

45

In [45]:
sample.mean()

81.0

3) add_prefix(prefix) - 인덱스 라벨 앞에 prefix 문자열을 추가

In [46]:
sample.add_prefix('big-')

big-a     85
big-b     90
big-c     75
big-d     55
big-e     45
big-f     90
big-g     95
big-h     85
big-i     90
big-j    100
dtype: int64

4) value_counts() - Series에 있는 데이터 값들의 개수

In [44]:
sample.value_counts()

90     3
85     2
100    1
55     1
75     1
45     1
95     1
dtype: int64

In [45]:
sample.value_counts(ascending=False)

90     3
85     2
100    1
55     1
75     1
45     1
95     1
dtype: int64

In [52]:
sample.value_counts(True) 
# 인자를 주면 첫번째 인자부터 할당함. 첫 인자가 normalize니까 이 인자를 True로 할당한 것  

90     0.3
85     0.2
100    0.1
55     0.1
75     0.1
45     0.1
95     0.1
dtype: float64

5) add(값) - Series의 데이터 각각에 값을 더하기

In [48]:
sample.add(5)

a     90
b     95
c     80
d     60
e     50
f     95
g    100
h     90
i     95
j    105
dtype: int64

In [57]:
sample[:5].add(5)

a    90
b    95
c    80
d    60
e    50
dtype: int64

In [58]:
sample[5:].add(10)

f    100
g    105
h     95
i    100
j    110
dtype: int64


<b>[Mini Quiz #1]</b> 앞에 5개의 데이터에는 5를 더하고, 나머지 5개의 데이터에는 10을 더하시오.


In [61]:
sample.add([5, 5, 5, 5, 5, 10, 10, 10, 10, 10])

a     90
b     95
c     80
d     60
e     50
f    100
g    105
h     95
i    100
j    110
dtype: int64

In [60]:
print(sample[:5].add(5), sample[5:].add(10))

a    90
b    95
c    80
d    60
e    50
dtype: int64 f    100
g    105
h     95
i    100
j    110
dtype: int64


In [64]:
sample[[0, 1, 2, 3, 4]] + 5,
sample[[5, 6, 7, 8, 9]] + 10

a    90
b    95
c    80
d    60
e    50
dtype: int64 f    100
g    105
h     95
i    100
j    110
dtype: int64


In [65]:
a = sample[[0, 1, 2, 3, 4]] + 5
b = sample[[5, 6, 7, 8, 9]] + 10

6) append(series) - 인자로 받은 series를 기존 series 뒤에 이어붙여서 하나의 series로 만든다.

In [69]:
sample.append(Series(50, index=['k']))

a     85
b     90
c     75
d     55
e     45
f     90
g     95
h     85
i     90
j    100
k     50
dtype: int64

7) isin(val_list) - Series에 있는 각각의 데이터들이 val_list에 포함되어 있는지 여부를 확인

In [50]:
sample.isin([90])

a    False
b     True
c    False
d    False
e    False
f     True
g    False
h    False
i     True
j    False
dtype: bool

<b>[Mini Quiz #2]</b> sample 데이터 내에 80이 있는지 확인하여 있으면 True, 없으면 False를 출력

In [55]:
90 in sample.values

True

In [80]:
sample.isin([80])

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
i    False
j    False
dtype: bool

In [81]:
sample.isin([90,95])

a    False
b     True
c    False
d    False
e    False
f     True
g     True
h    False
i     True
j    False
dtype: bool

<b>[Mini Quiz #3]</b> sample의 인덱스 내에 'h'가 있는지 확인하여 있으면 True, 없으면 False를 출력

In [57]:
'h' in sample.index

True

In [84]:
sample.index.isin(['h'])

array([False, False, False, False, False, False, False,  True, False,
       False])

8) apply(<i>func</i>) - Series의 값에 <i>func</i> 함수를 적용

In [94]:
# 원래 시리즈에서 제공하지 않는 함수를 내가 정의해서 쓰고 싶은 경우 ! 
# 값이 80 이상이면 good, 미만이면 bad
def get_grade(val):
    if val >=80:
        return 'Good'
    else:
        return 'Bad'

In [95]:
sample.apply(get_grade)

a    Good
b    Good
c     Bad
d     Bad
e     Bad
f    Good
g    Good
h    Good
i    Good
j    Good
dtype: object

In [96]:
# 익명함수 (이름이 없는 함수) 람다 
# 함수에는 파란색으로 이름부여하여 정의. 
# 나중에는 이름으로 함수 호출 
# 익명함수(람다함수)는 이름이 없다.
# 재사용하기가 어려움 
# 간단한 구문들을 한번만 쓰고 말 것을 간단하게 ! 

In [97]:
sample.apply(lambda val: 'Good' if val >= 80 else 'Bad')
# 익명함수는 메모리를 잡아먹지 않는다.
# 정의한다는 것은 어딘가에 저장해야하는 것이다. 메모리 안에 저장해야한다. 
# 익명은 저장 필요 없기 때문에 메모리상에 저장되지 않는다.

a    Good
b    Good
c     Bad
d     Bad
e     Bad
f    Good
g    Good
h    Good
i    Good
j    Good
dtype: object

## Series 인덱싱 - 원하는 데이터만 선택하기

1) 특정 인덱스 선택하기
- 숫자 인덱스와 인덱스 라벨 모두 가능

In [105]:
sample[4]

45

In [106]:
sample['e']

45

2) 여러 인덱스를 동시에 선택하기
- 선택하고자 하는 인덱스 목록을 리스트(List, [])로 전달

In [109]:
sample[[2, 4, 6]] # 겉의 대괄호는 색인, 안의 대괄호는 리스트라는 의미 

c    75
e    45
g    95
dtype: int64

In [110]:
sample[['c','e','g']]

c    75
e    45
g    95
dtype: int64

In [111]:
sample['c':'g'] # 문자 인덱스는 마지막 인덱스까지도 포함한다. (숫자는 마지막 인덱스 포함 안한다.)

c    75
d    55
e    45
f    90
g    95
dtype: int64

3)인덱스 슬라이싱 - 주어진 범위에 해당하는 데이터 선택
<img src="img/1강/Series-슬라이싱.jpg" alt="datetime" style="width: 500px;"/>

- start idx와 end idx는 생략이 가능
- start idx를 생략 -> 맨 첫 데이터부터 선택
- end idx를 생략 -> 데이터 끝까지 선택

In [60]:
sample[0:3]

a    85
b    90
c    75
dtype: int64

In [62]:
sample[7:]

h     85
i     90
j    100
dtype: int64

In [120]:
sample[-4:]

g     95
h     85
i     90
j    100
dtype: int64

4) 조건 색인(불리언 색인) : 조건을 활용한 인덱스 선택
- 조건에 충족하는 데이터만 선택하는 방법
- 매우 많이 활용되므로, 꼭 알고 있어야 함!
<img src="img/1강/조건색인1.jpg" alt="datetime" style="width: 1200px;"/>

In [121]:
boolean_idx = [False, False, False, False, False, 
               True, True, True, True, True]

In [122]:
sample[boolean_idx]

f     90
g     95
h     85
i     90
j    100
dtype: int64

In [129]:
# 조건색인 *** 많이 쓰인다고 한다.
over90 = (sample >= 90 )

In [130]:
result = over90.values

In [131]:
sample[result]

b     90
f     90
g     95
i     90
j    100
dtype: int64

In [63]:
sample[sample >= 90]

b     90
f     90
g     95
i     90
j    100
dtype: int64

- boolean index를 조건을 통해 생성할 수 있다. 
<img src="img/1강/조건색인2.jpg" alt="datetime" style="width: 1200px;"/>

<b>[Mini Quiz #4]</b> sample 데이터의 평균값보다 큰 데이터만 선택

In [65]:
data.head()

A    41
B    84
C    64
D    83
E    38
dtype: int64

In [132]:
overavg = sample > sample.mean()

In [172]:
data[data > data.mean()]

B    99
C    89
D    81
E    82
H    71
K    76
N    70
P    72
S    56
T    67
V    87
W    64
X    96
Y    61
dtype: int64

In [134]:
overavg
avgboolean = overavg.values

In [136]:
sample[overavg]

a     85
b     90
f     90
g     95
h     85
i     90
j    100
dtype: int64

<b>[Mini Quiz #5]</b> sample의 값이 50과 80 사이의 데이터만 선택

In [175]:
#** 
data[(50 <= data) & (data <= 80)]

A    53
H    71
K    76
N    70
P    72
S    56
T    67
W    64
Y    61
dtype: int64

In [72]:
list('ABCDEFG')

['A', 'B', 'C', 'D', 'E', 'F', 'G']

=============================================================
# 실습 문제 

In [3]:
import random
import pandas as pd
from pandas import Series

In [73]:
# 실습 데이터 생성
sample = random.sample(range(1,100),26) # 1~100사이의 값을 26개 생성하여 list로 반환
data = Series(sample, index = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'))
data

A    16
B    49
C    31
D    85
E    22
F    18
G    32
H    29
I    45
J    72
K    33
L    42
M    88
N    81
O    24
P    51
Q    43
R    58
S    46
T    38
U    57
V    71
W    83
X    68
Y    14
Z    28
dtype: int64

In [5]:
# 1) 인덱스 라벨이 'K' 항목의 값 출력
data['K']

30

In [6]:
# 2) 인덱스 라벨이 'A','F','C' 항목의 값 출력
data[['A','F','C']]

A    41
F    88
C    64
dtype: int64

In [7]:
# 3) 5번 인덱스부터 15번 인덱스까지의 항목 출력
data[5:16]

F    88
G     1
H    48
I    78
J    34
K    30
L    14
M    59
N    55
O    80
P    87
dtype: int64

In [8]:
# 4) 뒤에서 5개 항목 출력
data[-5:]

V    60
W    13
X    91
Y    18
Z    11
dtype: int64

In [12]:
# 5) data의 항목의 갯수를 출력 **
data.size

26

In [13]:
# 6) data 항목 값들의 평균보다 큰 항목만 출력 
## Hint. data 항목 값들의 평균은 data.mean()으로 구할 수 있다.
data[data > data.mean()]

B    84
C    64
D    83
F    88
I    78
M    59
N    55
O    80
P    87
Q    76
T    57
V    60
X    91
dtype: int64

In [74]:
# 7) data의 항목 값 중에 50이 있는지 확인하여, 있으면 True, 없으면 False를 출력
50 in data


False

In [77]:
# 8) data의 인덱스 라벨과 각 항목 값을 아래와 같이 출력
# index: A, value: XX
# index: B, value: XX
# index: C, value: XX
#data.add_prefix('index: ')
# data.items() : for문 사용할 때 쓰기. for문 돌게 준비하는 역할
for idx, val in data.items(): # 인덱스랑 값. 두개를 반환해야하니까 val 하나만 써놓으면 쩔수없이 튜플로 반환했던것. 
    print('index: ', idx, ', value: ',val)

index:  A , value:  16
index:  B , value:  49
index:  C , value:  31
index:  D , value:  85
index:  E , value:  22
index:  F , value:  18
index:  G , value:  32
index:  H , value:  29
index:  I , value:  45
index:  J , value:  72
index:  K , value:  33
index:  L , value:  42
index:  M , value:  88
index:  N , value:  81
index:  O , value:  24
index:  P , value:  51
index:  Q , value:  43
index:  R , value:  58
index:  S , value:  46
index:  T , value:  38
index:  U , value:  57
index:  V , value:  71
index:  W , value:  83
index:  X , value:  68
index:  Y , value:  14
index:  Z , value:  28
